# For fixing insecure wifi mess.
[openssl_init]
providers = provider_sect
ssl_conf = ssl_sect
  
[ssl_sect]
system_default = system_default_sect
  
[system_default_sect]
Options = UnsafeLegacyRenegotiation	
